import Reveal from "@/components/Reveal"; import Link from "next/link";
export const metadata={title:'About the Founder'};
export default function Founder(){return <><section className="page-hero"><div className="eyebrow">THE PERSON BEHIND THE PRACTICE</div><h1>Physiotherapy with a human point of view.</h1><p>Meet the people and principles behind Motion &amp; Mend in Koramangala.</p></section>
<Reveal><section className="service-detail founder-detail"><article className="detail-card founder-profile"><div className="founder-profile-head"><div className="founder-monogram">AM</div><div><div className="eyebrow">FOUNDER / LEAD PHYSIOTHERAPIST</div><h2>Dr. Arjun Malhotra</h2><p className="founder-role">Founder &amp; Lead Physiotherapist</p></div></div><div className="eyebrow">THE PRACTICE</div><h2>Built around people, not just injuries.</h2><p className="lead">Motion &amp; Mend began with a simple belief: patients deserve to understand what is happening, what they can do about it, and what progress should look like.</p><p>That means assessment before treatment, clear communication throughout rehabilitation, and plans that fit real life. The clinic’s work spans musculoskeletal pain, sports injuries, post-surgical rehabilitation and practical movement recovery.</p><p>The goal is not to make every session complicated. It is to make the path forward easier to follow.</p><Link className="cta" href="/contact">Start with a consultation →</Link></article><div className="detail-photo founder-portrait"><img src="https://images.pexels.com/photos/27298085/pexels-photo-27298085.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Concept portrait for Dr. Arjun Malhotra"/><span>CONCEPT PORTRAIT / REPLACE WITH CLIENT PHOTOGRAPH</span></div></section></Reveal>
<Reveal><section className="section"><div className="values founder-values">
<div className="value"><div className="eyebrow">WHAT MATTERS</div><h2 className="section-title">The clinic is built around three simple ideas.</h2><p>Good physiotherapy should be clinically thoughtful and genuinely usable outside the treatment room.</p></div>
<div className="value"><div className="icon">01</div><h3>Explain it clearly</h3><p>You should know what we are working on, why it matters and what to expect next.</p></div>
<div className="value"><div className="icon">02</div><h3>Train for real life</h3><p>Exercises and treatment should connect to the work, sport and everyday activities you want back.</p></div>
<div className="value"><div className="icon">03</div><h3>Measure the change</h3><p>Progress is easier to trust when milestones are visible and the plan changes when it needs to.</p></div>
</div></section></Reveal>
<Reveal><section className="section"><div className="closing-cta"><div><div className="eyebrow">MEET US IN KORAMANGALA</div><h2>Let’s make the next step less complicated.</h2><p>Start with a conversation about what is bothering you and what you want to get back to.</p></div><Link className="cta light" href="/contact">Contact Motion &amp; Mend →</Link></div></section></Reveal></> }